Split Templates in multiple types
Mirantis/hmc pull request #287
Opened 2024-09-09 19:46 UTC by eromanova

Closes #267

2024-09-11 00:14 UTC, slysunkin approved these changes

2024-09-11 10:51 UTC, Kshatrix requested changes

2024-09-11 10:51 UTC, Kshatrix commented on api/v1alpha1/template_types.go
> +type Template interface {
Let's keep this interface on the consumer side

2024-09-11 10:51 UTC, Kshatrix commented on api/v1alpha1/template_types.go
> +	UpdateStatus(context.Context, crclient.Client, TemplateStatusMixin) error
I don't think we need it. We could rather use crclient.Object interface here.

2024-09-11 10:51 UTC, Kshatrix commented on api/v1alpha1/template_types.go
> +type TemplateState struct {
I don't think we need a dedicated struct. Let's add getters that return pointers to status/spec instead.

2024-09-11 10:51 UTC, Kshatrix commented on api/v1alpha1/template_types.go
> +	Kind              TemplateKind        `json:"kind"`
GetObjectKind() will be accessible, so there's no need to have it separately

2024-09-11 10:51 UTC, Kshatrix commented on internal/controller/template_controller.go
> +			Namespace: r.SystemNamespace,
I think we want to use the namespace of associated Cluster/ServiceTemplate object here. SystemNamespace is only for ProviderTemplate (when Namespace is empty)

2024-09-12 11:12 UTC, Kshatrix approved these changes

2024-09-12 11:13 UTC, merged